### ISSUE TITLE
Looking for provide/inject example

### ISSUE THREAD

**Issue by josephting** [mcibique/vue-testing-examples#2]
Looking for example to properly mount components that uses provide / inject.

This sounds similar to [Dependency Injection](https://github.com/mcibique/vue-testing-examples#dependency-injection) but I'm lost.

Ref:
[Vue Docs](https://vuejs.org/v2/api/#provide-inject)
[Vue Test Utils](https://vue-test-utils.vuejs.org/api/options.html#provide)

**Comment by mcibique** [comment]
Sorry, I started implementing some examples in December but couldn't find any time to finish it and add some meaningful README for it.

https://github.com/mcibique/vue-testing-examples#testing-provideinject

hope it helps.
